use super::{map_tiles::MapTileState, simulation::*};

pub(super) struct AppDefaults {
    pub num_riders: usize,
    pub num_drivers: usize,
    pub initial_rider_count: usize,
    pub initial_driver_count: usize,
    pub request_window_hours: u64,
    pub driver_spread_hours: u64,
    pub simulation_duration_hours: u64,
    pub match_radius_km: f64,
    pub min_trip_km: f64,
    pub max_trip_km: f64,
    pub map_size_km: f64,
    pub rider_cancel_min_mins: u64,
    pub rider_cancel_max_mins: u64,
    pub seed_enabled: bool,
    pub seed_value: u64,
    pub matching_algorithm: MatchingAlgorithmType,
    pub batch_matching_enabled: bool,
    pub batch_interval_secs: u64,
    pub base_fare: f64,
    pub per_km_rate: f64,
    pub commission_rate: f64,
    pub surge_enabled: bool,
    pub surge_radius_k: u32,
    pub surge_max_multiplier: f64,
    pub max_willingness_to_pay: f64,
    pub max_acceptable_eta_min: u64,
    pub accept_probability: f64,
    pub max_quote_rejections: u32,
    pub driver_base_acceptance_score: f64,
    pub driver_fare_weight: f64,
    pub driver_pickup_distance_penalty: f64,
    pub routing_mode: RoutingMode,
    pub osrm_endpoint: String,
    pub traffic_profile_mode: TrafficProfileMode,
    pub congestion_zones_enabled: bool,
    pub dynamic_congestion_enabled: bool,
    pub base_speed_enabled: bool,
    pub base_speed_kmh: f64,
    pub spawn_mode: SpawnMode,
    pub map_tiles: MapTileState,
    pub start_year: i32,
    pub start_month: u32,
    pub start_day: u32,
    pub start_hour: u32,
    pub start_minute: u32,
}

impl AppDefaults {
    pub(super) fn new() -> Self {
        Self {
            num_riders: 80,
            num_drivers: 50,
            initial_rider_count: 0,
            initial_driver_count: 10,
            request_window_hours: 21,
            driver_spread_hours: 21,
            simulation_duration_hours: 24,
            match_radius_km: 11.0,
            min_trip_km: 1.0,
            max_trip_km: 25.0,
            map_size_km: 25.0,
            rider_cancel_min_mins: 6,
            rider_cancel_max_mins: 40,
            seed_enabled: true,
            seed_value: 123,
            matching_algorithm: MatchingAlgorithmType::Hungarian,
            batch_matching_enabled: true,
            batch_interval_secs: 20,
            base_fare: 1.20,
            per_km_rate: 1.00,
            commission_rate: 0.175,
            surge_enabled: true,
            surge_radius_k: 2,
            surge_max_multiplier: 2.0,
            max_willingness_to_pay: 50.0,
            max_acceptable_eta_min: 20,
            accept_probability: 0.8,
            max_quote_rejections: 3,
            driver_base_acceptance_score: 1.0,
            driver_fare_weight: 0.37,
            driver_pickup_distance_penalty: -0.7,
            routing_mode: RoutingMode::H3Grid,
            osrm_endpoint: "http://localhost:5000".to_string(),
            traffic_profile_mode: TrafficProfileMode::None,
            congestion_zones_enabled: false,
            dynamic_congestion_enabled: false,
            base_speed_enabled: false,
            base_speed_kmh: 50.0,
            spawn_mode: SpawnMode::Uniform,
            map_tiles: MapTileState::new(),
            start_year: 2026,
            start_month: 2,
            start_day: 3,
            start_hour: 6,
            start_minute: 30,
        }
    }
}
